import {
  Newspaper,
  MessageSquareX,
  Profi,
  UserRound,
  BadgeInfo,
  Settings,
  Settings2,
  SlidersHorizontal,
  LogOut,
  Plus,
  Upload,
  Image,
  X,
} from 'lucide-react';
export const icons = {
  copy: 'ooui:copy-ltr',
  edit: 'ooui:edit',
  delete: 'ooui:trash',
  comment: 'ic:baseline-insert-comment',
  // comment: 'ooui:ongoing-chat-ltr',
  profile: 'ooui:user-avatar',
  settings: 'ooui:settings',
  tag: 'ooui:tag-ltr',
  info: 'ooui:info-filled',
  favorite: 'ooui:heart',
  share: 'ooui:share',
  externalLink: 'ooui:new-window-ltr',
  ellipsis: 'ooui:ellipsis',
  filter: 'ooui:funnel-ltr',
  globe: 'ooui:globe',
  palestine: 'twemoji:flag-palestinian-territories',
  usa: 'twemoji:flag-united-states',
  send: 'lucide:send-horizontal',
  arrow: 'lucide:arrow-right',
  add: 'lucide:plus',
  exit: 'lucide:log-out',
  arrowUp: 'lucide:chevrons-up',
  email: 'lucide:mail',
  at: 'lucide:at-sign',
  lock: 'lucide:lock-keyhole',
  tags: 'lucide:tags',
  heartOutline: 'mdi:heart-outline',
  communication: 'fluent:communication-person-20-regular',
  messaging: 'icon-park-outline:communication',
  profileSettings: 'mdi:account-cog-outline',
  appSettings: 'ic:baseline-app-settings-alt',
  checkMark: 'line-md:confirm',
  filterAlt: 'material-symbols:filter-alt',
  verified: 'material-symbols:verified-outline-rounded',
  error: 'material-symbols:error-circle-rounded-outline-sharp',
  github: 'ph:github-logo-bold',
  telegram: 'tabler:brand-telegram',
  whatsapp: 'tabler:brand-whatsapp',
  dashboard: 'mage:dashboard',
  star: 'material-symbols:kid-star',
  starOutline: 'material-symbols:kid-star-outline',
  close: 'material-symbols:close-small-outline-rounded',
  offline: 'oui:offline',
  speedMeter: 'line-md:speedometer-loop',
  sync: 'material-symbols:directory-sync-rounded',
  users: 'ph:users-three-duotone',
  upload: 'material-symbols:upload-sharp',
  photos: 'material-symbols:photo-library-outline-rounded',
  specialStar: 'noto:eight-pointed-star',
  chats: 'ph:wechat-logo-bold',
  addChat: 'mage:message-dots-round-plus',
  usersGroup: 'ci:users-group',
  starBadge: 'material-symbols:award-star-outline-rounded',
  leftArrow: 'material-symbols:line-start-arrow-notch-rounded',
  post: 'ep:postcard',
  colorTheme: 'proicons:dark-theme',
};

export const Icons = {
  feed: Newspaper,
  messenger: MessageSquareX,
  profile: UserRound,
  info: BadgeInfo,
  settings: Settings2,
  controlPanel: SlidersHorizontal,
  logout: LogOut,
  add: Plus,
  upload: Upload,
  images: Image,
  cancel: X,
};
