CREATE TABLE IF NOT EXISTS "tags" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone,
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
DROP TABLE "reactions";--> statement-breakpoint
ALTER TABLE "conversation_member" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "from_id" SET NOT NULL;