ALTER TABLE "users_prefs" DROP CONSTRAINT "users_prefs_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "users_prefs" ADD PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "users_prefs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "users_prefs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "users_prefs" ADD COLUMN "user_id" integer NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "users_prefs" ADD CONSTRAINT "users_prefs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
